apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
stringData:
  admin-username: <your-keycloak-admin-username>
  admin-password: <your-keycloak-admin-password>
  db-username: <your-keycloak-db-username>
  db-password: <your-keycloak-db-password>
  client-secret: <your-keycloak-client-secret>
