spring.application.name=config
server.port=8888

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config/

management.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
