apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: registry.hogwarts-1.local/n11-bootcamp/shipping:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config:8888
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
