apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/config/

images:
  - name: registry.hogwarts-1.local/n11-bootcamp/config
    newTag: 2026.05.03.9

patches:
  - path: resources-patch.yaml
