spring.application.name=odev-2
server.port=${PORT:8080}

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:1}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:2}

app.security.bcrypt-strength=${BCRYPT_STRENGTH:10}
