apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-web
  template:
    metadata:
      labels:
        app: client-web
    spec:
      containers:
        - name: client-web
          image: registry.hogwarts-1.local/n11-bootcamp/client-web:latest
          imagePullPolicy: Always
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: production
            - name: COOKIE_SECURE
              value: "false"
            - name: INTERNAL_API_BASE_URL
              value: http://gateway:8080
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
