apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: registry.hogwarts-1.local/n11-bootcamp/eureka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            periodSeconds: 10
